#!/bin/bash

xhost +local:docker \
    && docker run \
        --rm \
        --detach \
        --user ufme \
        --env DISPLAY \
        --device /dev/dri \
        --volume /tmp/.X11-unix:/tmp/.X11-unix \
        --volume /dev/shm:/dev/shm \
        --volume ./fme_runtime:/home/ufme \
        fme-desktop

